name: Deploy to Google Colab

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-colab.txt
        pip install pytest pytest-cov
        
    - name: Run tests
      env:
        CI: true
      run: |
        python -m pytest tests/ -v --cov=showdown_gym --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        
    - name: Build package
      run: |
        python setup.py sdist bdist_wheel
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: showdown-gym-package
        path: dist/
        
    - name: Create Colab badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "🚀 [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/${{ github.repository }}/blob/main/colab_setup.ipynb)" >> colab_badge.md
        
    - name: Update README with Colab badge
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        # Add Colab badge to README if not present
        if ! grep -q "colab-badge" README.md; then
          echo "" >> README.md
          echo "## 🚀 Quick Start with Google Colab" >> README.md
          echo "" >> README.md
          echo "[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/${{ github.repository }}/blob/main/colab_setup.ipynb)" >> README.md
          echo "" >> README.md
          echo "Click the badge above to open this repository directly in Google Colab!" >> README.md
        fi
        
    - name: Commit changes
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Add Colab deployment badge" || exit 0
        git push
        
    - name: Deploy to PyPI (on release)
      if: github.event_name == 'release'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install twine
        twine upload dist/*
